# https://travis-ci.org/#!/translate/makeyfile
sudo: false
language: python
python:
  - 2.7
install:
  - pip install --upgrade pip
  - pip install .
  - pip install makeyfile[test]
  - pip freeze
  - git config --global user.email "travis@ci.com"
  - git config --global user.name "Travis Runner"

script:
  - makey -v travis-run

after_success:
  - makey send-coverage
